### ISSUE TITLE
Released version 1.3 cannot be used from Python 3

### ISSUE THREAD

**Issue by MatthiasBach** [kyrus/python-junit-xml#19]
The released version 1.3 from PyPI fails with `TabError: inconsistent use of tabs and spaces in indentation`. As the issue seems to be fixed in master, I would suggest to perform a new release. The issue can e.g. be seen in https://travis-ci.org/blue-yonder/devpi-builder/jobs/32638794.

**Comment by CyrilRoelandteNovance** [comment]
The bug report is quite old, but I have to agree: a new version would be nice. I'm currently facing the exact same trivial issue.

**Comment by brianebeyer** [comment]
Can you please check against v1.5 and let me know if this is still an issue? Apologies on the delay here.

**Comment by sandrotosi** [comment]
v1.4 worked fine with py3k, so I guess this can be closed

**Comment by MatthiasBach** [comment]
Sorry, this fell of my stack. Latest release (1.6) works great on Python 3.
