### ISSUE TITLE
Test suite and tox.ini are missing on PyPi

### ISSUE THREAD

**Issue by nblock** [kyrus/python-junit-xml#24]
Just noticed, that some files are missing in the junit-xml-1.4.tar.gz archive from PyPi: 
* test suite
* tox.ini
* …

**Comment by Ketouem** [comment]
It can be easily fixed by adding the missing files' names inside `MANIFEST.in` file located at the root of the project.

**Comment by sandrotosi** [comment]
yes please, in particular test_junit_xml.py would be really helpful in the PyPI tarball (as I'm packaging the library for Debian and we'd like to run tests at package build-time)

**Comment by brianebeyer** [comment]
@nblock Can you submit a PR for the `Manifest.in` fix separate from the flake8 changes? Not sure yet what to do with that PR since it changes a lot of files.

**Comment by nblock** [comment]
@brianebeyer I created pull request #30. Regarding #25, in the past I noticed several instances of whitespace/indentation errors. Those may be easily catched with flake8. Take your time to think about, I'll try to keep the pull request up-to-date with master until you decide about it.

**Comment by brianebeyer** [comment]
Fixed in #30

**Comment by brianebeyer** [comment]
@nblock @sandrotosi I wrapped these PR's into v1.5 and published to pypi. Thanks for your help and don't hesitate to let me know if I screwed anything up there.
