### ISSUE TITLE
Where are the docs?

### ISSUE THREAD

**Issue by chadhutchins182** [kyrus/python-junit-xml#48]
The readme and front page say 

> See the docs and unit tests for more examples.

However I cannot find any docs and the unit test file [https://github.com/kyrus/python-junit-xml/blob/master/test_junit_xml.py](url) doesn't have any comments in the code on what does what, some of it is self explanatory but not all IMO.

**Comment by brianebeyer** [comment]
The docs are here: https://github.com/kyrus/python-junit-xml/blob/master/README.rst

Unit tests are here: https://github.com/kyrus/python-junit-xml/blob/master/test_junit_xml.py
