### ISSUE TITLE
Request: new PyPI release

### ISSUE THREAD

**Issue by jdevera** [kyrus/python-junit-xml#65]
Much like #43 but again in October 2019. Let me know if I can help in any way.

**Comment by feffe** [comment]
Yes, please make a release of version 1.8.1 on pypi. Actually I would prefer if you bump the version to 1.9 as the interface changed from version 1.8.0 to 1.8.1 (still backward compatible). When we remove the deprecated interface we can bump to version 2.0.0

**Comment by rasendubi** [comment]
@brianebeyer could you please release version 1.9?

**Comment by brianebeyer** [comment]
Done!

**Comment by rasendubi** [comment]
Thank you! \o/
